// packages/chartkit-react-renderer/src/Chart.tsx
/**
 * A Chartkit chart, as a React component.
 *
 * The work happens in `@qkix/chartkit-core`, which turns a spec into a finished
 * SVG string. This is the thin part: hand that string to React.
 */

import { renderChart, type ChartSpec, type RenderOptions } from '@qkix/chartkit-core';
import type { ReactNode } from 'react';

export type ChartProps = {
  spec: ChartSpec;
  /**
   * Locale for number formatting. Worth passing explicitly on a server, where
   * the runtime default is whatever the container was built with.
   */
  locale?: string;
  /**
   * Prefix for the ids the chart's `aria-labelledby` points at. Required when a
   * page holds more than one chart, or their accessible names collide.
   */
  idPrefix?: string;
  className?: string;
  /**
   * Called when the spec will not render, instead of the chart. Without one,
   * an invalid spec renders nothing - the same as any other broken content, and
   * better than a half-drawn chart that looks like real data.
   */
  fallback?: (issues: { path: string; message: string }[]) => ReactNode;
};

export function Chart({ spec, locale, idPrefix, className, fallback }: ChartProps): ReactNode {
  const options: RenderOptions = { locale, idPrefix };
  const result = renderChart(spec, options);

  if (!result.ok) return fallback ? fallback(result.issues) : null;

  // The markup is this library's own output, built by a string builder that
  // escapes every author-controlled value on the way in - see chartkit-core's
  // svg.ts. Nothing from the spec reaches the page unescaped.
  return <div className={className} dangerouslySetInnerHTML={{ __html: result.svg }} />;
}

// packages/chartkit-vue-renderer/src/Chart.vue
<script setup lang="ts">
/**
 * A Chartkit chart, as a Vue component.
 *
 * The work happens in `@qkix/chartkit-core`, which turns a spec into a finished
 * SVG string. This is the thin part - and being thin is the point: the rendered
 * page carries an SVG and nothing else. No hydration work, no client-side chart
 * library, no bytes. The SVG is built synchronously, so the server and the
 * client produce identical markup.
 */
import { computed } from 'vue';

import { renderChart, type ChartSpec } from '@qkix/chartkit-core';

const props = defineProps<{
  spec: ChartSpec;
  /** Locale for number formatting. Worth passing explicitly when building on a server. */
  locale?: string;
  /** Prefix for the ids the accessible name points at. Needed when a page holds several charts. */
  idPrefix?: string;
}>();

// `class`, `style` and anything else the consumer puts on <Chart> is bound to
// the wrapper by hand, so nothing is left dangling when the chart draws nothing.
defineOptions({ inheritAttrs: false });

const result = computed(() =>
  renderChart(props.spec, { locale: props.locale, idPrefix: props.idPrefix })
);

// An invalid spec renders nothing, the same as any other broken content. A
// half-drawn chart would look like real data, which is worse than an absence.
const svg = computed(() => (result.value.ok ? result.value.svg : ''));
</script>

<template>
  <!-- The markup is this library's own output, from a builder that escapes every
       author-controlled value on the way in - see chartkit-core's svg.ts. -->
  <div v-if="svg" v-bind="$attrs" v-html="svg"></div>
</template>
